/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Clip = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Nat,
  'title' : IDL.Text,
  'endTime' : IDL.Nat,
  'createdAt' : IDL.Int,
  'videoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'createClip' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : IDL.Int })],
      [],
    ),
  'deleteClip' : IDL.Func([IDL.Nat], [], []),
  'getAllClips' : IDL.Func([], [IDL.Vec(Clip)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Clip = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Nat,
    'title' : IDL.Text,
    'endTime' : IDL.Nat,
    'createdAt' : IDL.Int,
    'videoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'createClip' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : IDL.Int })],
        [],
      ),
    'deleteClip' : IDL.Func([IDL.Nat], [], []),
    'getAllClips' : IDL.Func([], [IDL.Vec(Clip)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };